# This is a basic workflow to help you get started with Actions

name: Push to GCS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: | 
          ls 
    - id: upload-folder-dev
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: ../
        destination: zimi-dev-test-cdn-bucket
    - id: list-updated-files-dev
      run: | 
        echo ${{steps.upload-folder-dev.outputs.uploaded}}
        
    - id: upload-folder-prod
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.gcp_credentials_production }}
        path: ../
        destination: zimi-production-ota-cdn-bucket
    - id: list-updated-files-prod
      run: | 
        echo ${{steps.upload-folder-prod.outputs.uploaded}}        
        


